### ISSUE TITLE
unable to run face recognition demo 

### ISSUE THREAD

**Issue by peererror** [IndataLabsPublic/InData-Labs-FaceSDK#1]
I am getting following error 

```
Hello from the pygame community. https://www.pygame.org/contribute.html
Adding 5002.jpg from C:\Users\zahid\AppData\Roaming\OneScreen GoSafe\tomcat_v4\webapps\MIPS\res\gate\employee\123\Zahid
Traceback (most recent call last):
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\zahid\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\zahid\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main
    run()
  File "c:\Users\zahid\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "e:\InData-Labs-FaceSDK\demo\recognition_on_webcam.py", line 54, in <module>
    system.create_database_from_folders(folders_path)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\site-packages\face_recognition_sdk\utils\database.py", line 45, in create_database_from_folders
    self.sdk.add_photo_by_user_id(photo, user_id)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\site-packages\face_recognition_sdk\sdk.py", line 94, in add_photo_by_user_id
    self.add_descriptor(descriptor, user_id)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\site-packages\face_recognition_sdk\sdk.py", line 109, in add_descriptor
    self.database.add_descriptor(descriptor, user_id)
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\site-packages\face_recognition_sdk\modules\database\faiss\faiss_database.py", line 45, in add_descriptor
    self.index.add_with_ids(descriptor, np.array([user_id]))
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\site-packages\faiss\__init__.py", line 111, in replacement_add_with_ids
    self.add_with_ids_c(n, swig_ptr(x), swig_ptr(ids))
  File "C:\Users\zahid\.conda\envs\face_sdk\lib\site-packages\faiss\swigfaiss.py", line 6204, in add_with_ids
    return _swigfaiss.IndexIDMap_add_with_ids(self, n, x, xids)
TypeError: in method 'IndexIDMap_add_with_ids', argument 4 of type 'faiss::IndexIDMapTemplate< faiss::Index >::idx_t const *'
```

**Comment by IndataLabsPublic** [comment]
Hi! We updated our issues templates. Can you reopen your issue with a new template and with a more detailed description of your problem? Thanks!
